### ISSUE TITLE
'CausalImpact' object has no attribute 'inferences'

### ISSUE THREAD

**Issue by rodolfoocampo** [dafiti/causalimpact#52]
I am able to run CausalImpact() and generate a CausalImpact object, however, when I try to get a summary, I get the following error: 

AttributeError: 'CausalImpact' object has no attribute 'inferences'

**Comment by WillianFuks** [comment]
Hi @rodolfoocampo ,

Could you please share the code you are running? It seems as if the instantiation hasn't been completed for some reason.

**Comment by WillianFuks** [comment]
Hi @rodolfoocampo , just checking, do you still have this issue going on?

**Comment by rodolfoocampo** [comment]
Hi Willian,

I originally tried using my own data, however, using the code from the
example in the read me, I get the same problem. I am running the code in a
Google Colab notebook with a Python 3 runtime. Here's the notebook
<https://colab.research.google.com/drive/1fWGcMPDaWxV7V5NaBZQHkrbx43VQOIvV>
and the code is the following:

import pandas as pd
import numpy as np

!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import seaborn as sns
from dateutil.parser import parse
from google.colab import drive
import seaborn as sns
!pip install causalimpact
import numpy as np
import pandas as pd
from statsmodels.tsa.arima_process import ArmaProcess
from causalimpact import CausalImpact
drive.mount('/content/gdrive')

np.random.seed(12345)
ar = np.r_[1, 0.9]
ma = np.array([1])
arma_process = ArmaProcess(ar, ma)
X = 100 + arma_process.generate_sample(nsample=100)
y = 1.2 * X + np.random.normal(size=100)
y[70:] += 5

data = pd.DataFrame({'y': y, 'X': X}, columns=['y', 'X'])
pre_period = [0, 69]
post_period = [70, 99]

ci = CausalImpact(data, pre_period, post_period)
print(ci.summary())
print(ci.summary(output='report'))
ci.plot()

.

**Comment by WillianFuks** [comment]
Hi @rodolfoocampo ,

This seems to be related to an installation issue. 

In order to install our package you need to run:

    !pip install pycausalimpact

With the "py" at the beginning (this happened because when we started implementing this package there were already other packages with the name `causalimpact`; those repositories were no longer maintained so we decided to create this one).

I've uninstalled the previous package, installed this one instead, restarted the kernel and now it seems to be working.

Please let us know if this solves your issue :)

Best,

Will

**Comment by rodolfoocampo** [comment]
Oops, my bad! I just went along with the name of the repo. Thanks so much
for your help!

Best regards
