### ISSUE TITLE
KeyError 'exog' with statsmodels 0.11.0

### ISSUE THREAD

**Issue by freshsid** [dafiti/causalimpact#53]
When using the main example in the README.md file, the application crashes with this error 

`if model_args['exog'] is not None:
KeyError: 'exog'`

Revert statsmodels to version 0.10.2 will fix this error.

**Comment by WillianFuks** [comment]
Hi @freshsid ,

Thanks for opening this issue for us! You're right, something seems to have been broken for latest versions of statsmodels.

I'll check what's going on.

Thanks,

Will

**Comment by WillianFuks** [comment]
Hi @freshsid ,

We've just pushed a [fix](https://github.com/dafiti/causalimpact/pull/54) for this issue. As it turns out, for statsmodels version 0.11.0 the return of input keywords no longer included the key `exog` which is the error you observed; we updated the code to treat this accordingly.

The new code has already been published to PyPI so running `pip install -U pycausalimpact` should already bring the newly updated code.

Once again, thanks for opening this issue for us :)! If you have any problem please let us know.

Best,

Will
