### ISSUE TITLE
What to consider when the message on Causal Impact Report is conflicting?

### ISSUE THREAD

**Issue by GiovannaR** [dafiti/causalimpact#58]
Hi everyone,

I am trying to evaluate if the model is reliable, statistical significant and if the prediction is "good". But the Causal Impact Report is conflicting confirming that the model is not statistical significant at the same time it confirms it is statistical significant. What affirmations should I believe? The "Bayesian one-sided tail-area probability p" in the Report really shows if the model is reliable or not? If not, how can I evaluate that? 

Example of conflicting Report if the opposite affirmation in bold:

> Analysis report {CausalImpact}
During the post-intervention period, the response variable had
an average value of approx. 1.87. In the absence of an
intervention, we would have expected an average response of 1.68.
The 50% interval of this counterfactual prediction is [1.41, 1.9].
Subtracting this prediction from the observed response yields
an estimate of the causal effect the intervention had on the
response variable. This effect is 0.19 with a 50% interval of
[-0.03, 0.46]. For a discussion of the significance of this effect,
see below.
Summing up the individual data points during the post-intervention
period (which can only sometimes be meaningfully interpreted), the
response variable had an overall value of 3.74.
Had the intervention not taken place, we would have expected
a sum of 3.35. The 50% interval of this prediction is [2.83, 3.79].
The above results are given in terms of absolute numbers. In relative
terms, the response variable showed an increase of +11.42%. The 50%
interval of this percentage is [-1.61%, 27.17%].
**This means that, although the intervention appears to have caused a
positive effect, this effect is not statistically significant** when
considering the entire post-intervention period as a whole. Individual
days or shorter stretches within the intervention period may of course
still have had a significant effect, as indicated whenever the lower
limit of the impact time series (lower plot) was above zero.
The apparent effect could be the result of random fluctuations that
are unrelated to the intervention. This is often the case when the
intervention period is very long and includes much of the time when
the effect has already worn off. It can also be the case when the
intervention period is too short to distinguish the signal from the
noise. Finally, failing to find a significant effect can happen when
there are not enough control variables or when these variables do not
correlate well with the response variable during the learning period.
**The probability of obtaining this effect by chance is very small
(Bayesian one-sided tail-area probability p = 0.27).
This means the causal effect can be considered statistically
significant.**

**Comment by WillianFuks** [comment]
Hi @GiovannaR ,

As I can't simulate your data settings I can only suggest some ideas of what's happening:

This issue also happens in the original R package implementation as you can see [here](https://stats.stackexchange.com/questions/415087/causalimpact-conflicting-results-posterior-prob-v-confidence-interval). 

It's a similar question to yours. In the answer, you'll see the reference to the following example:

```
------------------------------------------------------------------------------
   Group |     Obs        Mean    Std. Err.   Std. Dev.   [95% Conf. Interval]
---------+--------------------------------------------------------------------
    male |      91    50.12088    1.080274    10.30516    47.97473    52.26703
  female |     109    54.99083    .7790686    8.133715    53.44658    56.53507
---------+--------------------------------------------------------------------
combined |     200      52.775    .6702372    9.478586    51.45332    54.09668
---------+--------------------------------------------------------------------
    diff |           -4.869947    1.304191               -7.441835   -2.298059
------------------------------------------------------------------------------
Degrees of freedom: 198
                  Ho: mean(male) - mean(female) = diff = 0
     Ha: diff < 0               Ha: diff != 0              Ha: diff > 0
       t =  -3.7341                t =  -3.7341              t =  -3.7341
   P < t =   0.0001          P > |t| =   0.0002          P > t =   0.9999
```
This is an example of a difference between male and female averages. Null hypothesis is `H0: mean_male = mean_female`.

The **two-sided test** has a p value of 0.0002. The **one-sided test** has 0.0001. Both these tests suggests us to reject H0 and accept Ha (which is either `diff < 0` or `diff != 0`). This is expected as the female average seems bigger than the male so either diff is different from zero or lower.

Notice though what happens for the one-sided test `Ha: diff > 0`. p value is 0.9999 which means reject Ha and keep H0! The conclusion would be that the averages are equal (it doesn't make much sense as females average seems bigger than males).

I've referenced this example because probably something similar happened in your case. This is a "edge case" and should be rare to happen, but sometimes it does.

What probably happened (still, remember that I'm supposing as I don't have access to the data) is that the first test (first bold text) is a **two-sided test**. It basically consists of observing whether the lower range of the prediction is negative while the upper is positive (which happens in your case). This is the equivalent of `diff != 0` in the previous example.

Then the second part of the report (second bold text) uses a **one-sided hypothesis testing** for finding signal, which in your case turned out to be similar to the `diff > 0` example as shown above.

So the big question is: what to do?

This is the tough part. It's hard to say the appropriate action without knowing the data and the context you're working on. Hopefully these points help you a bit:

- You are using alpha=50% instead of the usual 5%. Make sure that this is really what you want. The significance is so high that you are probably observing noise and concluding it's signal.
- Usually the two-sided tests is the standard choice in most packages. One sided is used given context (the link referenced before explains more on that).
- Your goals and analyzes might guide you on what is more relevant to test. If you want to test whether the effect changed something (for better or worse) then use two-sided. If you want to test if it changed in a given direction then one-sided.
- We recommend using in the Python package **std_prior_level** equal to `None`.

As said before, the conclusions will be similar for most cases but unfortunately for corner cases this might happen. In those cases we need to analyze what makes more sense, what data we are working with and the consequences of what happens in case of making the wrong decision (if there's a lot to lose for instance then one type of test might be more appropriate than the others).

If you want you can also apply some linear transformation and add white noise to your data and we can try analyzing it here to confirm this is what is happening. I suspect that this is the case so far.

If you have any questions let us know :)

Best,

Will

**Comment by GiovannaR** [comment]
Hi, @WillianFuks 

Your answer helped me a lot, thank you very much. But I am still confused about the meaning of some results, the final value of the causal effect is based on a one-sided test or on two-sided test? 

By final causal effect I mean this part of the summary output:

>Posterior Inference {Causal Impact}
                         Average            Cumulative
Actual                    1.07               2.14
Prediction (s.d.)         1.29 (0.55)        2.59 (1.1)
50% CI                    [0.93, 1.68]       [1.87, 3.36]
Absolute effect (s.d.)    -0.22 (0.55)       -0.44 (1.1)
50% CI                    [-0.61, 0.14]      [-1.22, 0.27]
Relative effect (s.d.)    -17.18% (42.65%)   -17.18% (42.65%)
50% CI                    [-46.94%, 10.6%]   [-46.94%, 10.6%]
Posterior tail-area probability p: 0.34
**Posterior prob. of a causal effect: 66.23%**

The `p_value` of the `causalimpact` is also originated of a two-sided test?

**Comment by WillianFuks** [comment]
Hi @GiovannaR ,

This `p-value` is obtained through one-sided test, you can check its computation [here](https://github.com/dafiti/causalimpact/blob/master/causalimpact/inferences.py#L425).

For the complete report (where you saw the conflicting messages) the two-sided test basically consists of verifying whether the Confidence Interval CI contains the value zero or not. It's actually the very first line of the template code as you can see [here](https://github.com/dafiti/causalimpact/blob/master/causalimpact/templates/report#L1).

The test basically is:

    {% set detected_sig = not (summary.average.rel_effect_lower < 0 and summary.average.rel_effect_upper > 0) -%}

Which is not the same as the p-value test (as discussed before).

That's how the original package was implemented and we decided to fully port to Python just as it was implemented in R (it should be fine for the most part, unfortunately corner cases still might happen).

**Comment by GiovannaR** [comment]
Thank you very much, I understood everything now.
